version: '3.9'
services:
  db:
    image: postgres:latest
    container_name: mars-egor
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mars-egor
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - db_network

volumes:
  db_data:

networks:
  db_network: